# Generated by Django 3.1.dev20190914151008 on 2019-10-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('car', models.CharField(max_length=200)),
                ('hometown', models.CharField(max_length=200)),
            ],
        ),
    ]
