# Generated by Django 3.1.dev20190914151008 on 2019-10-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_payment',
            field=models.CharField(choices=[(1, 'Venmo'), (2, 'Cash'), (3, 'Paypal'), (4, 'Check'), (5, 'Other')], default=1, max_length=6),
        ),
    ]
