# Generated by Django 2.2.6 on 2019-10-11 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0004_auto_20191007_1143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='users',
        ),
    ]
