# Generated by Django 2.2.6 on 2019-10-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0005_auto_20191010_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='na', max_length=200),
        ),
    ]
