# Generated by Django 2.2.6 on 2019-10-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0006_users_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
