# Generated by Django 2.2.5 on 2019-10-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0009_auto_20191013_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
