# Generated by Django 2.2.6 on 2019-10-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0010_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_payment',
            field=models.CharField(choices=[('venmo', 'Venmo'), ('cash', 'Cash'), ('red', 'Paypal'), ('orange', 'Check'), ('other', 'Other')], default=1, max_length=6),
        ),
    ]
