# Generated by Django 2.2.5 on 2019-10-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0013_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='request',
            name='author',
        ),
    ]
