# Generated by Django 2.2.5 on 2019-10-24 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0014_auto_20191021_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='return_date',
        ),
        migrations.AddField(
            model_name='request',
            name='depart_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='end_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_location',
            field=models.CharField(max_length=200),
        ),
    ]
