# Generated by Django 2.2.5 on 2019-10-24 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0015_auto_20191024_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='depart_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
