# Generated by Django 2.2.5 on 2019-10-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0016_auto_20191024_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='depart_time',
            field=models.TimeField(),
        ),
    ]
