# Generated by Django 2.2.5 on 2019-10-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0017_auto_20191024_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='requests',
        ),
    ]
