# Generated by Django 2.2.5 on 2019-10-28 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideshare', '0020_requests_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='depart_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='notes',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='seats',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='desired_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='notes',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_location',
            field=models.CharField(max_length=200),
        ),
    ]
