# Generated by Django 2.2.5 on 2019-11-11 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0021_auto_20191028_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='depart_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_location',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_location',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_payment',
            field=models.CharField(choices=[('Venmo', 'Venmo'), ('Cashapp', 'Cashapp'), ('Cash', 'Cash'), ('Paypal', 'Paypal'), ('Check', 'Check'), ('Other', 'Other')], default=1, max_length=7),
        ),
    ]
