# Generated by Django 2.2.5 on 2019-11-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0023_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='seats_open',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
