# Generated by Django 2.2.6 on 2019-11-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='car',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hometown',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_payment',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
