# Generated by Django 2.2.6 on 2019-12-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0007_auto_20191207_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='room_choice',
        ),
        migrations.AddField(
            model_name='room',
            name='notes',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='selected',
            field=models.IntegerField(default=0),
        ),
    ]
