# Generated by Django 2.2.6 on 2019-12-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0008_auto_20191207_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_choice',
            field=models.CharField(choices=[("Adam's Current Room", "Adam's Current Room"), ("Mike's Current Room", "Mike's Current Room"), ("Jeremy's Current Room", "Jeremy's Current Room"), ("Ryan's Current Room", "Ryan's Current Room"), ("Trevor's Current Room", "Trevor's Current Room"), ("Will's Current Room", "Will's Current Room"), ("Owen's Current Room", "Owen's Current Room")], default=1, max_length=30),
        ),
    ]
