# Generated by Django 2.2.6 on 2019-12-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0009_auto_20191207_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='original',
            field=models.IntegerField(default=0),
        ),
    ]
